export const COLLECTION = {
  USERS: 'users',
  NEWPOSTS: 'newPosts',
  ALLPOSTS: 'allPosts',
  BOOKMARKPOSTS: 'bookmarkPosts',
  MYPOSTS: 'myPosts',
  RECEIVEDPOSTS: 'receivedPosts',
  POSTS: 'posts',
  REPLIES: 'replies',
  // POSTPREVIEWS: 'postPreviews',
  LINKS: 'links',
  REJECTIONS: 'rejections',
  RECEIVABLEUSERS: 'receivableUsers',
  EXTRARECEIVABLEUSERS: 'extraReceivableUsers',
  GLOBALVARIABLES: 'globalVariables',
  PENDINGPOSTS: 'pendingPosts',
  PEDINGNEWPOSTS: 'pendingNewPosts',
};
