export const FIELD = {
  // LINKED_USER_DOC_IDS: 'linkedUserDocIds',
  LINKED_COUNT: 'linkedCount',
  CREATED_DATE: 'createdDate',
  DELETED_DATE: 'deletedDate',
  IS_ACTIVATED: 'isActivated',
  REPLY_COUNT: 'replyCount',
  USER_DOC_ID: 'userDocId',
  DATE: 'date',
  REJECTED_DATE: 'rejectedDate',
  LINKED_DATE: 'linkedDate',
  LAST_CONSECUTIVE_REJECTED_TIMES: 'lastConsecutiveRejectedTimes',
  IS_USING_EXTRA: 'isUsingExtra',
  SEARCH_FLAG: 'searchFlag',
  TOTAL_RECEIVABLE: 'totalReceivable',
  RECEIVABLE_COUNT: 'receivableCount',
  IS_ACCEPTED: 'isAccepted',
  TOKENS: 'tokens',
  CURRENT_RECEIVED_USER_DOC_ID: 'currentReceivedUserDocId',
  IS_READING: 'isReading',
  PRIMARY_LANGUAGE: 'primaryLanguage',
};
