export const FIELD = {
  LINKEDUSERDOCIDS: 'linkedUserDocIds',
  LINKEDCOUNT: 'linkedCount',
  CREATEDDATE: 'createdDate',
  ISACTIVEATED: 'isActivated',
  REPLYCOUNT: 'replyCount',
  USERDOCID: 'userDocId',
  DATE: 'date',
  REJECTEDDATE: 'rejectedDate',
  LINKEDDATE: 'linkedDate',
  LASTCONSECUTIVEREJECTEDTIMES: 'lastConsecutiveRejectedTimes',
  ISUSINGEXTRA: 'isUsingExtra',
  SEARCHFLAG: 'searchFlag',
  TOTAlRECEIVABLE: 'totalReceivable',
  RECEIVABLECOUNT: 'receivableCount',
  ISACTIVATED: 'isActivated',
};
