export const FIELD = {
  // LINKEDUSERDOCIDS: 'linkedUserDocIds',
  LINKEDCOUNT: 'linkedCount',
  CREATEDDATE: 'createdDate',
  DELETEDDATE: 'deletedDate',
  ISACTIVATED: 'isActivated',
  REPLYCOUNT: 'replyCount',
  USERDOCID: 'userDocId',
  DATE: 'date',
  REJECTEDDATE: 'rejectedDate',
  LINKEDDATE: 'linkedDate',
  LASTCONSECUTIVEREJECTEDTIMES: 'lastConsecutiveRejectedTimes',
  ISUSINGEXTRA: 'isUsingExtra',
  SEARCHFLAG: 'searchFlag',
  TOTAlRECEIVABLE: 'totalReceivable',
  RECEIVABLECOUNT: 'receivableCount',
  ISACCEPTED: 'isAccepted',
  DEVICETOKENS: 'tokens',
  CURRENTRECEIVEDUSERDOCID: 'currentReceivedUserDocId',
  ISREADING: 'isReading',
};
